# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Build
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: |
          make
