name: Code Analysis

on:
  push:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/code.analysis.yml"

env:
  GO_VERSION: "1.20"

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION}}

      - name: Revive Action
        uses: morphy2k/revive-action@v2.2.0

      - name: Check formatting
        run: test -z $(gofmt -l .) || (gofmt -l . && exit 1)

      - name: misspell
        uses: sobolevn/misspell-fixer-action@0.1.0
